(function() {
		tinymce.PluginManager.add('_jm_ds_mce_button', function( editor, url ) {
			editor.addButton( '_jm_ds_mce_button', {
				icon: false,
				type: 'button',
				text: 'Dashicons',
				tooltip: 'Dashicons shortcode',
				
				onclick: function() {
				
				
				    var icon_i = function(id) {
						return '<i class="dashicons-before dashicons-' + id + '"></i>';
					}
								
					editor.windowManager.open( {
	
						title: editor.getLang('jm_ds_tinymce_plugin.popup_title'),
						body: [
						
							{
								type: 'listbox',
								name: 'nameValue',
								label: 'Dashicons',
								
								values: [ // I know I'm a beginner but it works ^^ It's probably easy to reduce these lines of code
									{text: 'menu', value: 'menu', icon:' dashicons-before dashicons-menu'},
									//{text: 'admin-site', value: 'admin-site', icon:' dashicons-before dashicons-admin-site'},
									{text: 'dashboard', value: 'dashboard', icon:' dashicons-before dashicons-dashboard'},
									{text: 'admin-post', value: 'admin-post', icon:' dashicons-before dashicons-admin-post'},
									{text: 'admin-media', value: 'admin-media', icon:' dashicons-before dashicons-admin-media'},
									{text: 'admin-links', value: 'admin-links', icon:' dashicons-before dashicons-admin-links'},
									{text: 'admin-page', value: 'admin-page', icon:' dashicons-before dashicons-admin-page'},
									{text: 'admin-comments', value: 'admin-comments', icon:' dashicons-before dashicons-admin-comments'},
									{text: 'admin-appearance', value: 'admin-appearance', icon:' dashicons-before dashicons-admin-appearance'},
									{text: 'admin-plugins', value: 'admin-plugins', icon:' dashicons-before dashicons-admin-plugins'},
									{text: 'admin-users', value: 'admin-users', icon:' dashicons-before dashicons-admin-users'},
									{text: 'admin-tools', value: 'admin-tools', icon:' dashicons-before dashicons-admin-tools'},
									{text: 'admin-settings', value: 'admin-settings', icon:' dashicons-before dashicons-admin-settings'},
									{text: 'admin-network', value: 'admin-network', icon:' dashicons-before dashicons-admin-network'},
									{text: 'admin-home', value: 'admin-home', icon:' dashicons-before dashicons-admin-home'},
									{text: 'admin-generic', value: 'admin-generic', icon:' dashicons-before dashicons-admin-generic'},
									{text: 'admin-collapse', value: 'admin-collapse', icon:' dashicons-before dashicons-admin-collapse'},
									{text: 'welcome-write-blog', value: 'welcome-write-blog', icon:' dashicons-before dashicons-welcome-write-blog'},
									//{text: 'welcome-edit-page', value: 'welcome-edit-page', icon:' dashicons-before dashicons-welcome-edit-page'},
									{text: 'welcome-add-page', value: 'welcome-add-page', icon:' dashicons-before dashicons-welcome-add-page'},
									{text: 'welcome-view-site', value: 'welcome-view-site', icon:' dashicons-before dashicons-welcome-view-site'},
									{text: 'welcome-widgets-menus', value: 'welcome-widgets-menus', icon:' dashicons-before dashicons-welcome-widgets-menus'},
									{text: 'welcome-comments', value: 'welcome-comments', icon:' dashicons-before dashicons-welcome-comments'},
									{text: 'welcome-learn-more', value: 'welcome-learn-more', icon:' dashicons-before dashicons-welcome-learn-more'},
									//{text: 'format-standard', value: 'format-standard', icon:' dashicons-before dashicons-format-standard'},
									{text: 'format-aside', value: 'format-aside', icon:' dashicons-before dashicons-format-aside'},
									{text: 'format-image', value: 'format-image', icon:' dashicons-before dashicons-format-image'},
									{text: 'format-gallery', value: 'format-gallery', icon:' dashicons-before dashicons-format-gallery'},
									{text: 'format-video', value: 'format-video', icon:' dashicons-before dashicons-format-video'},
									{text: 'format-status', value: 'format-status', icon:' dashicons-before dashicons-format-status'},
									{text: 'format-quote', value: 'format-status', icon:' dashicons-before dashicons-format-quote'},
									//{text: 'format-links', value: 'format-links', icon:' dashicons-before dashicons-format-links'},
									{text: 'format-chat', value: 'format-chat', icon:' dashicons-before dashicons-format-chat'},
									{text: 'format-audio', value: 'format-audio', icon:' dashicons-before dashicons-format-audio'},
									{text: 'camera', value: 'camera', icon:' dashicons-before dashicons-camera'},
									{text: 'images-alt', value: 'images-alt', icon:' dashicons-before dashicons-images-alt'},
									{text: 'images-alt2', value: 'images-alt2', icon:' dashicons-before dashicons-images-alt2'},
									{text: 'video-alt', value: 'video-alt', icon:' dashicons-before dashicons-video-alt'},
									{text: 'video-alt2', value: 'video-alt', icon:' dashicons-before dashicons-video-alt2'},
									{text: 'video-alt3', value: 'video-alt3', icon:' dashicons-before dashicons-video-alt3'},
									{text: 'media-archive', value: 'media-archive', icon:' dashicons-before dashicons-media-archive'},
									{text: 'media-audio', value: 'media-audio', icon:' dashicons-before dashicons-media-audio'},
									{text: 'media-code', value: 'media-code', icon:' dashicons-before dashicons-media-code'},
									{text: 'media-default', value: 'media-default', icon:' dashicons-before dashicons-media-default'},
									{text: 'media-document', value: 'media-document', icon:' dashicons-before dashicons-media-document'},
									{text: 'media-interactive', value: 'media-interactive', icon:' dashicons-before dashicons-media-interactive'},
									{text: 'media-spreadsheet', value: 'media-spreadsheet', icon:' dashicons-before dashicons-media-spreadsheet'},
									{text: 'media-text', value: 'media-text', icon:' dashicons-before dashicons-media-text'},
									{text: 'media-video', value: 'media-video', icon:' dashicons-before dashicons-media-video'},
									{text: 'playlist-audio', value: 'playlist-audio', icon:' dashicons-before dashicons-playlist-audio'},
									{text: 'playlist-video', value: 'playlist-video', icon:' dashicons-before dashicons-playlist-video'},
									{text: 'image-crop', value: 'image-crop', icon:' dashicons-before dashicons-image-crop'},
									{text: 'image-rotate-left', value: 'image-rotate-left', icon:' dashicons-before dashicons-image-rotate-left'},
									{text: 'image-rotate-right', value: 'image-rotate-right', icon:' dashicons-before dashicons-image-rotate-right'},
									{text: 'image-flip-vertical', value: 'image-flip-vertical', icon:' dashicons-before dashicons-image-flip-vertical'},
									{text: 'image-flip-horizontal', value: 'image-flip-horizontal', icon:' dashicons-before dashicons-image-flip-horizontal'},
									{text: 'undo', value: 'undo', icon:' dashicons-before dashicons-undo'},
									{text: 'redo', value: 'redo', icon:' dashicons-before dashicons-redo'},
									{text: 'editor-bold', value: 'editor-bold', icon:' dashicons-before dashicons-editor-bold'},
									{text: 'editor-italic', value: 'editor-italic', icon:' dashicons-before dashicons-editor-italic'},
									{text: 'editor-ul', value: 'editor-ul', icon:' dashicons-before dashicons-editor-ul'},
									{text: 'editor-ol', value: 'editor-ol', icon:' dashicons-before dashicons-editor-ol'},
									{text: 'editor-quote', value: 'editor-quote', icon:' dashicons-before dashicons-editor-quote'},
									{text: 'editor-alignleft', value: 'editor-alignleft', icon:' dashicons-before dashicons-editor-alignleft'},
									{text: 'editor-aligncenter', value: 'editor-aligncenter', icon:' dashicons-before dashicons-editor-aligncenter'},
									{text: 'editor-alignright', value: 'editor-alignright', icon:' dashicons-before dashicons-editor-alignright'},
									{text: 'editor-insertmore', value: 'editor-insertmore', icon:' dashicons-before dashicons-editor-insertmore'},
									{text: 'editor-spellcheck', value: 'editor-spellcheck', icon:' dashicons-before dashicons-editor-spellcheck'},
									//{text: 'editor-distractionfree', value: 'editor-distractionfree', icon:' dashicons-before dashicons-editor-distractionfree'}, 
									{text: 'editor-expand', value: 'editor-expand', icon:' dashicons-before dashicons-editor-expand'},
									{text: 'editor-contract', value: 'editor-contract', icon:' dashicons-before dashicons-editor-contract'},
									{text: 'editor-kitchensink', value: 'editor-kitchensink', icon:' dashicons-before dashicons-editor-kitchensink'},
									{text: 'editor-underline', value: 'editor-underline', icon:' dashicons-before dashicons-editor-underline'},
									{text: 'editor-justify', value: 'editor-justify', icon:' dashicons-before dashicons-editor-justify'},
									{text: 'editor-textcolor', value: 'editor-textcolor', icon:' dashicons-before dashicons-editor-textcolor'},
									{text: 'editor-paste-word', value: 'editor-paste-word', icon:' dashicons-before dashicons-editor-paste-word'},
									{text: 'editor-paste-text', value: 'editor-paste-text', icon:' dashicons-before dashicons-editor-paste-text'},
									{text: 'editor-removeformatting', value: 'editor-removeformatting', icon:' dashicons-before dashicons-editor-removeformatting'},
									{text: 'editor-video', value: 'editor-video', icon:' dashicons-before dashicons-editor-video'},
									{text: 'editor-customchar', value: 'editor-customchar', icon:' dashicons-before dashicons-editor-customchar'},
									{text: 'editor-outdent', value: 'editor-outdent', icon:' dashicons-before dashicons-editor-outdent'},
									{text: 'editor-indent', value: 'editor-indent', icon:' dashicons-before dashicons-editor-indent'},
									{text: 'editor-help', value: 'editor-help', icon:' dashicons-before dashicons-editor-help'},
									{text: 'editor-strikethrough', value: 'editor-strikethrough', icon:' dashicons-before dashicons-editor-strikethrough'},
									{text: 'editor-unlink', value: 'editor-unlink', icon:' dashicons-before dashicons-editor-unlink'},
									{text: 'editor-rtl', value: 'editor-rtl', icon:' dashicons-before dashicons-editor-rtl'},
									{text: 'editor-break', value: 'editor-break', icon:' dashicons-before dashicons-editor-break'},
									{text: 'editor-code', value: 'editor-code', icon:' dashicons-before dashicons-editor-code'},
									{text: 'editor-paragraph', value: 'editor-paragraph', icon:' dashicons-before dashicons-editor-paragraph'},
									{text: 'align-left', value: 'align-left', icon:' dashicons-before dashicons-align-left'},
									{text: 'align-right', value: 'align-right', icon:' dashicons-before dashicons-align-right'},
									{text: 'align-center', value: 'align-center', icon:' dashicons-before dashicons-align-center'},
									{text: 'align-none', value: 'align-none', icon:' dashicons-before dashicons-align-none'},
									{text: 'lock', value: 'lock', icon:' dashicons-before dashicons-lock'},
									{text: 'calendar', value: 'calendar', icon:' dashicons-before dashicons-calendar'},
									{text: 'visibility', value: 'visibility', icon:' dashicons-before dashicons-visibility'},
									{text: 'post-status', value: 'post-status', icon:' dashicons-before dashicons-post-status'},
									{text: 'edit', value: 'edit', icon:' dashicons-before dashicons-edit'},
									{text: 'trash', value: 'trash', icon:' dashicons-before dashicons-trash'},
									{text: 'external', value: 'external', icon:' dashicons-before dashicons-external'},
									{text: 'arrow-up', value: 'arrow-up', icon:' dashicons-before dashicons-arrow-up'},
									{text: 'arrow-down', value: 'arrow-down', icon:' dashicons-before dashicons-arrow-down'},
									{text: 'arrow-right', value: 'arrow-right', icon:' dashicons-before dashicons-arrow-right'},
									{text: 'arrow-left', value: 'arrow-left', icon:' dashicons-before dashicons-arrow-left'},
									{text: 'arrow-up-alt', value: 'arrow-up-alt', icon:' dashicons-before dashicons-arrow-up-alt'},
									{text: 'arrow-down-alt', value: 'arrow-up-alt', icon:' dashicons-before dashicons-arrow-down-alt'},
									{text: 'arrow-right-alt', value: 'arrow-right-alt', icon:' dashicons-before dashicons-arrow-right-alt'},
									{text: 'arrow-left-alt', value: 'arrow-left-alt', icon:' dashicons-before dashicons-arrow-left-alt'},
									{text: 'arrow-up-alt2', value: 'arrow-up-alt2', icon:' dashicons-before dashicons-arrow-up-alt2'},
									{text: 'arrow-down-alt2', value: 'arrow-down-alt2', icon:' dashicons-before dashicons-arrow-down-alt2'},
									{text: 'arrow-right-alt2', value: 'arrow-right-alt2', icon:' dashicons-before dashicons-arrow-right-alt2'},
									{text: 'arrow-left-alt2', value: 'arrow-left-alt2', icon:' dashicons-before dashicons-arrow-left-alt2'},
									{text: 'sort', value: 'sort', icon:' dashicons-before dashicons-sort'},
									{text: 'leftright', value: 'leftright', icon:' dashicons-before dashicons-leftright'},
									{text: 'randomize', value: 'randomize', icon:' dashicons-before dashicons-randomize'},
									{text: 'list-view', value: 'list-view', icon:' dashicons-before dashicons-list-view'},
									{text: 'exerpt-view', value: 'exerpt-view', icon:' dashicons-before dashicons-excerpt-view'},
									{text: 'share', value: 'share', icon:' dashicons-before dashicons-share'},
									{text: 'share-alt', value: 'share-alt', icon:' dashicons-before dashicons-share-alt'},
									{text: 'share-alt2', value: 'share-alt2', icon:' dashicons-before dashicons-share-alt2'},
									{text: 'twitter', value: 'twitter', icon:' dashicons-before dashicons-twitter'},
									{text: 'rss', value: 'rss', icon:' dashicons-before dashicons-rss'},
									{text: 'email', value: 'email', icon:' dashicons-before dashicons-email'},
									{text: 'email-alt', value: 'email-alt', icon:' dashicons-before dashicons-email-alt'},
									{text: 'facebook', value: 'facebook', icon:' dashicons-before dashicons-facebook'},
									{text: 'facebook-alt', value: 'facebook-alt', icon:' dashicons-before dashicons-facebook-alt'},
									{text: 'googleplus', value: 'googleplus', icon:' dashicons-before dashicons-googleplus'},
									{text: 'networking', value: 'networking', icon:' dashicons-before dashicons-networking'},
									{text: 'hammer', value: 'hammer', icon:' dashicons-before dashicons-hammer'},
									{text: 'art', value: 'art', icon:' dashicons-before dashicons-art'},
									{text: 'migrate', value: 'migrate', icon:' dashicons-before dashicons-migrate'},
									{text: 'performance', value: 'performance', icon:' dashicons-before dashicons-performance'},
									{text: 'universal-access', value: 'universal-access', icon:' dashicons-before dashicons-universal-access'},
									{text: 'universal-access-alt', value: 'universal-access-alt', icon:' dashicons-before dashicons-universal-access-alt'},
									{text: 'tickets', value: 'tickets', icon:' dashicons-before dashicons-tickets'},
									{text: 'nametag', value: 'nametag', icon:' dashicons-before dashicons-nametag'},
									{text: 'clipboard', value: 'clipboard', icon:' dashicons-before dashicons-clipboard'},
									{text: 'heart', value: 'heart', icon:' dashicons-before dashicons-heart'},
									{text: 'megaphone', value: 'megaphone', icon:' dashicons-before dashicons-megaphone'},
									{text: 'schedule', value: 'schedule', icon:' dashicons-before dashicons-schedule'},
									{text: 'wordpress', value: 'wordpress', icon:' dashicons-before dashicons-wordpress'},
									{text: 'wordpress-alt', value: 'wordpress-alt', icon:' dashicons-before dashicons-wordpress-alt'},
									{text: 'pressthis', value: 'pressthis', icon:' dashicons-before dashicons-pressthis'},
									{text: 'update', value: 'update', icon:' dashicons-before dashicons-update'},
									{text: 'screenoptions', value: 'screenoptions', icon:' dashicons-before dashicons-screenoptions'},
									{text: 'info', value: 'info', icon:' dashicons-before dashicons-info'},
									{text: 'cart', value: 'cart', icon:' dashicons-before dashicons-cart'},
									{text: 'feedback', value: 'cart', icon:' dashicons-before dashicons-feedback'},
									{text: 'cloud', value: 'cloud', icon:' dashicons-before dashicons-cloud'},
									{text: 'translation', value: 'translation', icon:' dashicons-before dashicons-translation'},
									{text: 'tag', value: 'tag', icon:' dashicons-before dashicons-tag'},
									{text: 'category', value: 'category', icon:' dashicons-before dashicons-category'},
									{text: 'archive', value: 'archive', icon:' dashicons-before dashicons-archive'},
									{text: 'tagcloud', value: 'tagcloud', icon:' dashicons-before dashicons-tagcloud'},
									{text: 'text', value: 'text', icon:' dashicons-before dashicons-text'},
									{text: 'yes', value: 'yes', icon:' dashicons-before dashicons-yes'},
									{text: 'no', value: 'no', icon:' dashicons-before dashicons-no'},
									{text: 'no-alt', value: 'no-alt', icon:' dashicons-before dashicons-no-alt'},
									{text: 'plus', value: 'plus', icon:' dashicons-before dashicons-plus'},
									{text: 'plus-alt', value: 'plus-alt', icon:' dashicons-before dashicons-plus-alt'},
									{text: 'minus', value: 'minus', icon:' dashicons-before dashicons-minus'},
									{text: 'dismiss', value: 'dismiss', icon:' dashicons-before dashicons-dismiss'},
									{text: 'marker', value: 'marker', icon:' dashicons-before dashicons-marker'},
									{text: 'star-filled', value: 'star-filled', icon:' dashicons-before dashicons-star-filled'},
									{text: 'star-half', value: 'star-half', icon:' dashicons-before dashicons-star-half'},
									{text: 'star-empty', value: 'star-empty', icon:' dashicons-before dashicons-star-empty'},
									{text: 'flag', value: 'flag', icon:' dashicons-before dashicons-flag'},
									{text: 'location', value: 'location', icon:' dashicons-before dashicons-location'},
									{text: 'location-alt', value: 'location-alt', icon:' dashicons-before dashicons-location-alt'},
									{text: 'vault', value: 'vault', icon:' dashicons-before dashicons-vault'},
									{text: 'shield', value: 'shield', icon:' dashicons-before dashicons-shield'},
									{text: 'shield-alt', value: 'shield-alt', icon:' dashicons-before dashicons-shield-alt'},
									{text: 'sos', value: 'sos', icon:' dashicons-before dashicons-sos'},
									{text: 'search', value: 'search', icon:' dashicons-before dashicons-search'},
									{text: 'slides', value: 'slides', icon:' dashicons-before dashicons-slides'},
									{text: 'analytics', value: 'analytics', icon:' dashicons-before dashicons-analytics'},
									{text: 'chart-pie', value: 'chart-pie', icon:' dashicons-before dashicons-chart-pie'},
									{text: 'chart-bar', value: 'chart-bar', icon:' dashicons-before dashicons-chart-bar'},
									{text: 'chart-line', value: 'chart-line', icon:' dashicons-before dashicons-chart-line'},
									{text: 'chart-area', value: 'chart-area', icon:' dashicons-before dashicons-chart-area'},
									{text: 'groups', value: 'groups', icon:' dashicons-before dashicons-groups'},
									{text: 'businessman', value: 'businessman', icon:' dashicons-before dashicons-businessman'},
									{text: 'id', value: 'id', icon:' dashicons-before dashicons-id'},
									{text: 'id-alt', value: 'id-alt', icon:' dashicons-before dashicons-id-alt'},
									{text: 'products', value: 'products', icon:' dashicons-before dashicons-products'},
									{text: 'awards', value: 'awards', icon:' dashicons-before dashicons-awards'},
									{text: 'forms', value: 'forms', icon:' dashicons-before dashicons-forms'},
									{text: 'testimonial', value: 'testimonial', icon:' dashicons-before dashicons-testimonial'},
									{text: 'portfolio', value: 'portfolio', icon:' dashicons-before dashicons-portfolio'},
									{text: 'book', value: 'book', icon:' dashicons-before dashicons-book'},
									{text: 'book-alt', value: 'book-alt', icon:' dashicons-before dashicons-book-alt'},
									{text: 'download', value: 'download', icon:' dashicons-before dashicons-download'},
									{text: 'upload', value: 'upload', icon:' dashicons-before dashicons-upload'},
									{text: 'backup', value: 'backup', icon:' dashicons-before dashicons-backup'},
									{text: 'clock', value: 'clock', icon:' dashicons-before dashicons-clock'},
									{text: 'lightbulb', value: 'lightbulb', icon:' dashicons-before dashicons-lightbulb'},
									{text: 'microphone', value: 'microphone', icon:' dashicons-before dashicons-microphone'},
									{text: 'desktop', value: 'desktop', icon:' dashicons-before dashicons-desktop'},
									{text: 'tablet', value: 'tablet', icon:' dashicons-before dashicons-tablet'},
									{text: 'smartphone', value: 'smartphone', icon:' dashicons-before dashicons-smartphone'},
									{text: 'smiley', value: 'smiley', icon:' dashicons-before dashicons-smiley'}
								],
							   
							    onPostRender: function() {
									// Select this dash item by default
									this.value('star-filled');
								}

							},
								
							{
								type: 'textbox',
								name: 'colorValue',
								label: editor.getLang('jm_ds_tinymce_plugin.color_input'),
								value: '#222222'
							},
							
							{
								type: 'textbox',
								name: 'sizeValue',
								label: editor.getLang('jm_ds_tinymce_plugin.size_input'),
								maxLength: 2,
								value: '2'
							},
							{
								type: 'textbox',
								name: 'textValue',
								label: editor.getLang('jm_ds_tinymce_plugin.access_input'),
								value: ''
							},
							{
								type: 'textbox',
								name: 'classValue',
								label: editor.getLang('jm_ds_tinymce_plugin.css_class_input'),
								value: 'jm-ds-icon'
							}

						],
						onsubmit: function( e ) {
							editor.insertContent( '[dashicon name="' + e.data.nameValue + '" color="' + e.data.colorValue + '" size="' + e.data.sizeValue + '" class="' + e.data.classValue + '" text="' + e.data.textValue + '"]');
						}
					});
				}
			});
		});
	})();